; Visit http://d1stats.ru/configdota/ for details
[HOTKEYS]

;You can use Alt, Shift and Ctrl modifiers like "ShiftQ" for Shift+Q or "CtrlW" for Ctrl+W. Leave empty if you don't want to use them.
;Binded keys are active in menus and able to override WC3 hotkeys
;You can chose special hotkeys from the list here https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx
;To use special hotkeys enter them as 0x (hex representation), f.i. 0x70 for F1, 0x71 for F2, shift0x71 for Shift+F2, and so on
;Skill slots 5 and 6 - the one in the middle above normal skills
;Command panel
SkillSlot1 = Q
SkillSlot2 = W
SkillSlot3 = E
SkillSlot4 = R

;SkillSlot5 can also be used to learn "Attribute bonus" inside hero skills menu
SkillSlot5 = D
SkillSlot6 = F

;Quick Cast - instantly applies the spell to the target under cursor
QuickCastSlot1 = 
QuickCastSlot2 = 
QuickCastSlot3 = 
QuickCastSlot4 = 
QuickCastSlot5 = 
QuickCastSlot6 = 
QuickCastInventorySlot1 = 
QuickCastInventorySlot2 = 
QuickCastInventorySlot3 = 
QuickCastInventorySlot4 = 
QuickCastInventorySlot5 = 
QuickCastInventorySlot6 = 

;Autocasts
ASkillSlot1 = 
ASkillSlot2 = 
ASkillSlot3 = 
ASkillSlot4 = 
ASkillSlot5 = 
ASkillSlot6 = 

;Full panel rebinding
;Use this in case if you wanna rebind default buttons
BindMove = M
BindStop = S
BindHold = H
BindPatrol = P
BindAttack = A
BindOpenHeroSkills = Y

;Hotkeys for buttons located in the cells of Move, Stop, Hold & Patrol (1,2,3,5 respectively)
ExtraSlot1 = 
ExtraSlot2 = 
ExtraSlot3 = 
ExtraSlot5 = 

;Inventory
;Items declaration goes as 1, 2 for the top row, 3, 4 for the middle row, and 5, 6 for the bottom row
ItemSlot1 = SPACE
ItemSlot2 = 
ItemSlot3 = 
ItemSlot4 = 
ItemSlot5 = 
ItemSlot6 = 

;HUD
DisplayScoreboard = 

;Shops
ShopsQWERTY = false

;Selection related hotkeys
SelectAllUnits = 
SelectAllOtherUnits = 
SelectBestCourier = 
SelectCircleOfPower = 

;Allows to control all available units at once by issuing order while holding the hotkey
OrderToAllControlledUnitsHotkey = 

;Other
;Display neutral spawn (block) rectangle, can only use single key (no combinations allowed), space or F1-F12, 0x12 for Alt.
DisplayNeutralsSpawnAreaHotkey = 0x12
DisplayTowerRangeHotkey = 0x12

;Disables AltQ, AltS, AltH etc hotkeys from opening ingame menus
DisableDefaultAltHotkeys = false

;Or you can chose which to disable
DisableAltS = false
DisableAltL = false
DisableAltH = false
DisableAltO = false
DisableAltQ = false
DisableAltG = false
DisableAltT = false
DisableAltA = false
DisableAltR = false
DisableAltF = false
DisableAllDefaultHotkeys=false 
SelectYourHero=

[GAMEOPTIONS]
MaxFPS = 64
AutoFPSLimit = false
DisplayFPSCounter = false
LockMouseAtWindow = false
AutoselectHero = true
DotA2HPBars = false
DisplayManabars = true
WideScreen = true
TeleportationCanOnlyBeStoppedSoft = true
TeleportationCanOnlyBeStopped = false
AutoselectSummonedUnitsRadius = 2500
CloseWC3EveryGame = false
DoubleClickHelperEnabled = true
AutoattackEnabled = true
AutoattackDisabledByStopOnly = false
;Only works if autoattack disabled (false)
SmartAttackEnabled = false
RightClickDeny = false
SelectionHelperEnabled = false
PersonalLatency = 100
KeepLegacyCourierButtonsLayout = false
BlinkAutoShifting = false
IAmShy=false
IDontWantToVisitSite=false

[HEROOPTIONS]
Juggernaut_HealingWardDoNotFollow = true
Meepo_NumbersOverheadClones = true

[VISUALS]
Weather = 
FogDensity = 192
AlwaysDisplayRangeMarkers = true
AlwaysDisplayHPRegen = false
SameSelectionCircleForEveryone = false
AdvancedTooltips = true
DisplayRegeneration = true
CustomFPSInfo = true
EscClearsChat = true
EscClearsPlayersChat = true
GoodMinimap = false
ProperColorsForCreeps = false
AlliesAlwaysGreen = false
BetterFPS = false
BetterFPS2 = false
BetterFPS3 = false
DisableDefaultSpace = false
DisableDefaultMouseWheel = false
DisableDefaultTilde = false
ShowTipsWhileDead = true
ShowItemsInMultiboard = false
UseAdvancedHUD = false
DisableAltTogglingHPBars = false
WaterColor = 
IgnoreAllChat = false
HideHeroNames = false
RepeatGameMessagesIntoChatLog = false
AlwaysShowCourierButton = false
HideMinimapSignals = false
ColorblindMode = false
AdvancedStatsIconDisabled = false
ClassicIngameTime = true
CameraHeight = 
SmoothFogReveal = false
HealingDisplaysAmount = true
KeepStopHoldButtons = false
DisableHeroCornerButton = false
HideHeroIcon = false
ChatMessageDuration=10.0
DisplayAllyGoldOnSelection=false
EnableSoundOfGoldCoins=true

[QUICKCHAT]

;By pressing the hotkey text will be send into the chat
QuickChatText1 = 
QuickChatHotkey1 = 
QuickChatText2 = 
QuickChatHotkey2 = 
QuickChatText3 = 
QuickChatHotkey3 = 
QuickChatText4 = 
QuickChatHotkey4 = 
QuickChatText5 = 
QuickChatHotkey5 = 
QuickChatText6 = 
QuickChatHotkey6 = 
QuickChatText7 = 
QuickChatHotkey7 = 
QuickChatText8 = 
QuickChatHotkey8 = 
QuickChatText9 = 
QuickChatHotkey9 = 
QuickChatText10 = 
QuickChatHotkey10 = 

[ONSTART]
StartChatString1 = 
StartChatString2 = 
StartChatString3 = 
StartChatString4 = 
StartChatString5 = 
StartChatString6 = 
StartChatString7 = 
StartChatString8 = 
StartChatString9 = 
StartChatString10 = 
StartChatString11 = 
StartChatString12 = 
StartChatString13 = 
StartChatString14 = 
StartChatString15 = 
StartChatString16 = 
StartChatString17 = 
StartChatString18 = 
StartChatString19 = 
StartChatString20 = 
StartChatString21 = 

[DEBUG]
DisableTexttags = false
StatsSent=false
[GAMEPLAY]
TotalGamesCounter=2
[HEROSETS]
DisabledHeroSkins=0
DisableMySexyAnnouncer=false
